# Site settings
title: The Blog of Christian Munte
email: mail@munte.me
description: >
  Where Christian Munte talks about nonsense that is sometimes coherent.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.munte.me" # the base hostname & protocol for your site
paginate: 5 # The number of posts to show per page on your homepage

name: 'Christian Munte'
bio: >
  Software engineer with a passion for all things tech.
  Also enjoys talks of travel and finance.
author_image: "/assets/images/author.jpg"
twitter_username: cmunte132
github_username:  pieiscool32

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  parse_block_html: true

gems:
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME