# Site settings
title: The Blog of Christian Munte
email: mail@munte.me
description: >
  Where I talk about nonsense that is sometimes coherent.
logo: "/assets/images/logo.jpg"
baseurl: ""
url: "https://blog.munte.me"
paginate: 5

name: 'Christian Munte'
bio: >
  Software engineer with a passion for all things tech.
  Also enjoys talks of travel and finance.
author_image: "/assets/images/author.jpg"
twitter_username: cmunte132
linkedin_username: cmunte132
github_username: pieiscool32

# Google Analytics
analytics_id: "UA-64461045-4"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  parse_block_html: true

plugins:
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME